services:
  Redis:
    # you can also use \RedisArray, \RedisCluster or \Predis\Client classes
    class: Redis
    calls:
      - connect:
          - '%env(REDIS_HOST)%'
          - '%env(int:REDIS_PORT)%'
      - auth:
          - '%env(REDIS_PASSWORD)%'
  Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
    arguments:
      - '@Redis'
      - { prefix: 'sess_' }
