services:
  Redis:
    # you can also use \RedisArray, \RedisCluster or \Predis\Client classes
    class: Redis
    calls:
      - connect:
          - '%env(REDIS_HOST)%'
          - '%env(int:REDIS_PORT)%'
      - auth:
          - '%env(REDIS_PASSWORD)%'
#  RedisAdapter:
#    class: Symfony\Component\Cache\Adapter\RedisAdapter
#    calls:
#      - createConnection:
#          - '%env(REDIS_URL)%'
#    arguments:
#      - '@Redis'
  Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
    arguments:
#      - '@=service("RedisAdapter").createConnection()'
      - '@Redis'
      - { prefix: 'sess_' }
